import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const mainContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		// Never used by the plugin runtime (eval-harness-only code path); must
		// not be inlined here — it ships inside reranker.worker.js instead.
		'@huggingface/transformers',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
});

// Separate bundle so the transformers.js runtime + ONNX model loading stay
// entirely off the main plugin bundle and the UI thread.
const workerContext = await esbuild.context({
	entryPoints: ['src/search/reranker.worker.ts'],
	outfile: 'reranker.worker.js',
	bundle: true,
	format: 'iife',
	target: 'es2020',
	logLevel: "info",
	sourcemap: false,
	treeShaking: true,
	legalComments: 'none',
});

if (prod) {
	await mainContext.rebuild();
	await workerContext.rebuild();
	process.exit(0);
} else {
	await mainContext.watch();
	await workerContext.watch();
}
